classdef AN1_EstimationErrors < PostProcess
    % Plot the estimation errors during the simulations together with their
    % RMSE and 3sigma values

    methods

        function obj = AN1_EstimationErrors(varargin)
            % Get data
            if isempty(varargin)
                [name,path] = uigetfile;
                data = strcat(path,name);
                data_file = matfile(data);
            else
                data_file = varargin{1};
            end

            % Initialize parent class
            obj = obj@PostProcess(data_file);

            errors = obj.data_file.est_errors;
            uncertainties = obj.data_file.est_three_sigma;

            % Reshape data as ([sim nan sim ecc..], variable)
            xm_reshaped = squeeze(reshape(permute(cat(2,...
                permute(cat(3,errors.xm),[3 2 1]),...
                nan*ones(length(errors),1,3)),[2 1 3]),[],1,3));
            vm_reshaped = squeeze(reshape(permute(cat(2,...
                permute(cat(3,errors.vm),[3 2 1]),...
                nan*ones(length(errors),1,3)),[2 1 3]),[],1,3));
            xb_reshaped = squeeze(reshape(permute(cat(2,...
                permute(cat(3,errors.xb),[3 2 1]),...
                nan*ones(length(errors),1,3)),[2 1 3]),[],1,3));
            vb_reshaped = squeeze(reshape(permute(cat(2,...
                permute(cat(3,errors.vb),[3 2 1]),...
                nan*ones(length(errors),1,3)),[2 1 3]),[],1,3));
            attitude_reshaped = squeeze(reshape(permute(cat(2,...
                permute(cat(3,errors.attitude),[3 2 1]),...
                nan*ones(length(errors),1,3)),[2 1 3]),[],1,3));
            bias_g_reshaped = squeeze(reshape(permute(cat(2,...
                permute(cat(3,errors.bias_gyro),[3 2 1]),...
                nan*ones(length(errors),1,3)),[2 1 3]),[],1,3));
            bias_c_reshaped = squeeze(reshape(permute(cat(2,...
                permute(cat(3,errors.bias_clock),[3 2 1]),...
                nan*ones(length(errors),1,1)),[2 1 3]),[],1));
            drift_c_reshaped = squeeze(reshape(permute(cat(2,...
                permute(cat(3,errors.drift_clock),[3 2 1]),...
                nan*ones(length(errors),1,1)),[2 1 3]),[],1));
            aging_c_reshaped = squeeze(reshape(permute(cat(2,...
                permute(cat(3,errors.aging_clock),[3 2 1]),...
                nan*ones(length(errors),1,1)),[2 1 3]),[],1));

            % Compute 3 sigma and RMSE values of the estimated errors
            [average.xm, RMSE.xm, real_3sigma.xm, est_3sigma.xm] =...
                obj.get_stoch_params(cat(3, errors.xm), cat(3, uncertainties.xm));
            [average.vm, RMSE.vm, real_3sigma.vm, est_3sigma.vm] =...
                obj.get_stoch_params(cat(3, errors.vm), cat(3, uncertainties.vm));
            [average.xb, RMSE.xb, real_3sigma.xb, est_3sigma.xb] =...
                obj.get_stoch_params(cat(3, errors.xb), cat(3, uncertainties.xb));
            [average.vb, RMSE.vb, real_3sigma.vb, est_3sigma.vb] =...
                obj.get_stoch_params(cat(3, errors.vb), cat(3, uncertainties.vb));
            [average.attitude, RMSE.attitude, real_3sigma.attitude, est_3sigma.attitude] =...
                obj.get_stoch_params(cat(3, errors.attitude), cat(3, uncertainties.attitude));
            [average.bias_g, RMSE.bias_g, real_3sigma.bias_g, est_3sigma.bias_g] =...
                obj.get_stoch_params(cat(3, errors.bias_gyro), cat(3, uncertainties.bias_gyro));
            [average.bias_c, RMSE.bias_c, real_3sigma.bias_c, est_3sigma.bias_c] =...
                obj.get_stoch_params(cat(3, errors.bias_clock), cat(3, uncertainties.bias_clock));
            [average.drift_c, RMSE.drift_c, real_3sigma.drift_c, est_3sigma.drift_c] =...
                obj.get_stoch_params(cat(3, errors.drift_clock), cat(3, uncertainties.drift_clock));
            [average.aging_c, RMSE.aging_c, real_3sigma.aging_c, est_3sigma.aging_c] =...
                obj.get_stoch_params(cat(3, errors.aging_clock), cat(3, uncertainties.aging_clock));

            %% PLOTS
            % Tranform matrix into single vector separated by NaNs for
            % better plots
            time_reshaped = [errors(1).Time' nan];
            for i = 2:length(errors)
                time_reshaped = [time_reshaped errors(i).Time' nan];
            end

            % Plot Main SC Pos Vel
            x_data = repmat({cat(1,{time_reshaped./3600},...
                {[errors(1).Time./3600;nan;errors(1).Time./3600]},...
                {[errors(1).Time./3600;nan;errors(1).Time./3600]},{errors(1).Time./3600})},6,1);
            y_data = { {xm_reshaped(:,1),[average.xm(1,:)+real_3sigma.xm(1,:)...
                nan average.xm(1,:)-real_3sigma.xm(1,:)],[est_3sigma.xm(1,:) nan -est_3sigma.xm(1,:)],RMSE.xm(1,:)},...
                {xm_reshaped(:,2),[average.xm(2,:)+real_3sigma.xm(2,:),...
                nan,average.xm(2,:)-real_3sigma.xm(2,:)],[est_3sigma.xm(2,:) nan -est_3sigma.xm(2,:)],RMSE.xm(2,:)},...
                {xm_reshaped(:,3),[average.xm(3,:)+real_3sigma.xm(3,:),...
                nan,average.xm(3,:)-real_3sigma.xm(3,:)],[est_3sigma.xm(3,:) nan -est_3sigma.xm(3,:)],RMSE.xm(3,:)},...
                {vm_reshaped(:,1),[average.vm(1,:)+real_3sigma.vm(1,:),...
                nan,average.vm(1,:)-real_3sigma.vm(1,:)],[est_3sigma.vm(1,:) nan -est_3sigma.vm(1,:)],RMSE.vm(1,:)},...
                {vm_reshaped(:,2),[average.vm(2,:)+real_3sigma.vm(2,:),...
                nan,average.vm(2,:)-real_3sigma.vm(2,:)],[est_3sigma.vm(2,:) nan -est_3sigma.vm(2,:)],RMSE.vm(2,:)},...
                {vm_reshaped(:,3),[average.vm(3,:)+real_3sigma.vm(3,:),...
                nan,average.vm(3,:)-real_3sigma.vm(3,:)],[est_3sigma.vm(3,:) nan -est_3sigma.vm(3,:)],RMSE.vm(3,:)}...
                };
            title = 'AN1_MainError';
            WHratio = 1.2;
            perchTextWidth = 0.9;
            changeLineStyle = true;
            zoom_x = {[340 350],[340 350],[340 350],[340 350],[340 350],[340 350]};

            label_x = repmat({'Time [h]'},6,1);
            label_y = {'$x$ [km]','$y$ [km]','$z$ [km]',...
                '$v_x$ [km/s]','$v_y$ [km/s]','$v_z$ [km/s]'};
            ax_legend = true;
            legend = {'Errors','real $3\sigma$','est $3\sigma$','RMSE'};
            obj.plot_2D('x_data',x_data,'y_data',y_data,'label_x',label_x,...
                'label_y',label_y,'sub_cols',3,'sub_rows',2,'names',legend,...
                'ax_legend',ax_legend,'title',title,'WHratio',WHratio,...
                'percTextWidth',perchTextWidth,'changeLineStyle',changeLineStyle);
            obj.plot_2D('x_data',x_data,'y_data',y_data,'label_x',label_x,...
                'label_y',label_y,'sub_cols',3,'sub_rows',2,'names',legend,...
                'ax_legend',ax_legend,'title',title+"_zoom",'WHratio',WHratio,...
                'percTextWidth',perchTextWidth,'changeLineStyle',changeLineStyle,...
                'lim_x',zoom_x);

            % Plot Beacon SC Pos Vel
            
              
            x_data = repmat({cat(1,{time_reshaped(1:1:end)./3600},...
                {[errors(1).Time./3600;nan;errors(1).Time./3600]},...
                {[errors(1).Time./3600;nan;errors(1).Time./3600]},{errors(1).Time./3600})},6,1);
            y_data = { {xb_reshaped(:,1),[average.xb(1,:)+real_3sigma.xb(1,:)...
                nan average.xb(1,:)-real_3sigma.xb(1,:)],[est_3sigma.xb(1,:) nan -est_3sigma.xb(1,:)],RMSE.xb(1,:)},...
                {xb_reshaped(:,2),[average.xb(2,:)+real_3sigma.xb(2,:),...
                nan,average.xb(2,:)-real_3sigma.xb(2,:)],[est_3sigma.xb(2,:) nan -est_3sigma.xb(2,:)],RMSE.xb(2,:)},...
                {xb_reshaped(:,3),[average.xb(3,:)+real_3sigma.xb(3,:),...
                nan,average.xb(3,:)-real_3sigma.xb(3,:)],[est_3sigma.xb(3,:) nan -est_3sigma.xb(3,:)],RMSE.xb(3,:)},...
                {vb_reshaped(:,1),[average.vb(1,:)+real_3sigma.vb(1,:),...
                nan,average.vb(1,:)-real_3sigma.vb(1,:)],[est_3sigma.vb(1,:) nan -est_3sigma.vb(1,:)],RMSE.vb(1,:)},...
                {vb_reshaped(:,2),[average.vb(2,:)+real_3sigma.vb(2,:),...
                nan,average.vb(2,:)-real_3sigma.vb(2,:)],[est_3sigma.vb(2,:) nan -est_3sigma.vb(2,:)],RMSE.vb(2,:)},...
                {vb_reshaped(:,3),[average.vb(3,:)+real_3sigma.vb(3,:),...
                nan,average.vb(3,:)-real_3sigma.vb(3,:)],[est_3sigma.vb(3,:) nan -est_3sigma.vb(3,:)],RMSE.vb(3,:)}...
                };

            title = 'AN1_BeaconError';
            label_x = repmat({'Time [h]'},6,1);
             label_y = {'$x$ [km]','$y$ [km]','$z$ [km]',...
                '$v_x$ [km/s]','$v_y$ [km/s]','$v_z$ [km/s]'};
            ax_legend = true;
            legend = {'Errors','real $3\sigma$','est $3\sigma$','RMSE'};
            obj.plot_2D('x_data',x_data,'y_data',y_data,'label_x',label_x,...
                'label_y',label_y,'sub_cols',3,'sub_rows',2,'names',legend,...
                'ax_legend',ax_legend,'title',title,'WHratio',WHratio,...
                'percTextWidth',perchTextWidth,'changeLineStyle',changeLineStyle);

            % Plot Attitude
            
            x_data = repmat({cat(1,{time_reshaped./3600},...
                {[errors(1).Time./3600;nan;errors(1).Time./3600]},...
                {[errors(1).Time./3600;nan;errors(1).Time./3600]},{errors(1).Time./3600})},3,1);
            y_data = { {attitude_reshaped(:,1),...
                [average.attitude(1,:)+real_3sigma.attitude(1,:) nan average.attitude(1,:)-real_3sigma.attitude(1,:)]...
                [est_3sigma.attitude(1,:) nan -est_3sigma.attitude(1,:)],RMSE.attitude(1,:)},...
                {attitude_reshaped(:,2),...
                [average.attitude(2,:)+real_3sigma.attitude(2,:),nan,average.attitude(2,:)-real_3sigma.attitude(2,:)]...
                [est_3sigma.attitude(2,:) nan -est_3sigma.attitude(2,:)],RMSE.attitude(2,:)},...
                {attitude_reshaped(:,3),...
                [average.attitude(3,:)+real_3sigma.attitude(3,:),nan,average.attitude(3,:)-real_3sigma.attitude(3,:)]...
                [est_3sigma.attitude(3,:) nan -est_3sigma.attitude(3,:)],RMSE.attitude(3,:)},...
                };
            label_x = repmat({'Time [h]'},3,1);
            label_y = {'$x$[rad]','$y$[rad]','$z$ [rad]'};
            ax_legend = true;
            title = 'AN1_Attitude';
            WHratio = 1.3;
            perchTextWidth = 0.7;
            legend = {'Errors','real $3\sigma$','est $3\sigma$','RMSE'};
            obj.plot_2D('x_data',x_data,'y_data',y_data,'label_x',label_x,...
                'label_y',label_y,'sub_cols',1,'sub_rows',3,'names',legend,...
                'DMS_angles',false,'ax_legend',ax_legend,'title',title,'WHratio',WHratio,...
                'percTextWidth',perchTextWidth,'changeLineStyle',changeLineStyle);

            obj.plot_2D('x_data',x_data(1:2),'y_data',y_data(1:2),'label_x',label_x(1:2),...
                'label_y',label_y(1:2),'sub_cols',1,'sub_rows',2,'names',legend,...
                'DMS_angles',false,'ax_legend',ax_legend,'title',title+"_zoom",...
                'WHratio',WHratio,'percTextWidth',perchTextWidth,'changeLineStyle',changeLineStyle,...
                'lim_x',{[29 30],[153 159]});
            
            % Plot bias gyro
                y_data = { {bias_g_reshaped(:,1),...
                [average.bias_g(1,:)+real_3sigma.bias_g(1,:) nan average.bias_g(1,:)-real_3sigma.bias_g(1,:)]...
                [est_3sigma.bias_g(1,:) nan -est_3sigma.bias_g(1,:)],RMSE.bias_g(1,:)},...
                {bias_g_reshaped(:,2),...
                [average.bias_g(2,:)+real_3sigma.bias_g(2,:),nan,average.bias_g(2,:)-real_3sigma.bias_g(2,:)]...
                [est_3sigma.bias_g(2,:) nan -est_3sigma.bias_g(2,:)],RMSE.bias_g(2,:)},...
                {bias_g_reshaped(:,3),...
                [average.bias_g(3,:)+real_3sigma.bias_g(3,:),nan,average.bias_g(3,:)-real_3sigma.bias_g(3,:)]...
                [est_3sigma.bias_g(3,:) nan -est_3sigma.bias_g(3,:)],RMSE.bias_g(3,:)},...
                };
            label_x = repmat({'Time [h]'},3,1);
            label_y = {'$x$ [rad/s]','$y$ [rad/s]','$z$ [rad/s]'};
            ax_legend = true;
            title = 'AN1_gyro_bias';
            WHratio = 1.3;
            perchTextWidth = 0.7;
            legend = {'Errors','real $3\sigma$','est $3\sigma$','RMSE'};
            obj.plot_2D('x_data',x_data,'y_data',y_data,'label_x',label_x,...
                'label_y',label_y,'sub_cols',1,'sub_rows',3,...
                'DMS_angles',false,'ax_legend',ax_legend,'names',legend,...
                'title',title,'WHratio',WHratio,...
                'percTextWidth',perchTextWidth,'changeLineStyle',changeLineStyle);

            % Plot clock errors
             x_data = repmat({cat(1,{time_reshaped(1:1:end)./3600},...
                {[errors(1).Time./3600;nan;errors(1).Time./3600]},...
                {[errors(1).Time./3600;nan;errors(1).Time./3600]},{errors(1).Time./3600})},6,1);
            y_data = { {bias_c_reshaped,...
                [average.bias_c+real_3sigma.bias_c(1,:) nan average.bias_c-real_3sigma.bias_c]...
                [est_3sigma.bias_c nan -est_3sigma.bias_c],RMSE.bias_c},...
                {drift_c_reshaped,...
                [average.drift_c+real_3sigma.drift_c,nan,average.drift_c-real_3sigma.drift_c]...
                [est_3sigma.drift_c nan -est_3sigma.drift_c],RMSE.drift_c},...
                {aging_c_reshaped,...
                [average.aging_c+real_3sigma.aging_c,nan,average.aging_c-real_3sigma.aging_c]...
                [est_3sigma.aging_c nan -est_3sigma.aging_c],RMSE.aging_c},...
                {bias_g_reshaped(:,1),...
                [average.bias_g(1,:)+real_3sigma.bias_g(1,:) nan average.bias_g(1,:)-real_3sigma.bias_g(1,:)]...
                [est_3sigma.bias_g(1,:) nan -est_3sigma.bias_g(1,:)],RMSE.bias_g(1,:)},...
                {bias_g_reshaped(:,2),...
                [average.bias_g(2,:)+real_3sigma.bias_g(2,:),nan,average.bias_g(2,:)-real_3sigma.bias_g(2,:)]...
                [est_3sigma.bias_g(2,:) nan -est_3sigma.bias_g(2,:)],RMSE.bias_g(2,:)},...
                {bias_g_reshaped(:,3),...
                [average.bias_g(3,:)+real_3sigma.bias_g(3,:),nan,average.bias_g(3,:)-real_3sigma.bias_g(3,:)]...
                [est_3sigma.bias_g(3,:) nan -est_3sigma.bias_g(3,:)],RMSE.bias_g(3,:)}...
                };
            label_x = repmat({'Time [h]'},6,1);
            label_y = {'Bias [km]','Drift [km/s]','Aging [km/s$^2$]',...
                '$x$ [rad/s]','$y$ [rad/s]','$z$ [rad/s]'};
            ax_legend = true;
            legend = {'Errors','real $3\sigma$','est $3\sigma$','RMSE'};
            lim_y = {[-1 1], [-2e-5 2e-5], [-0.3e-10 0.3e-10],[-2e-5 2e-5],[-2e-5 2e-5],[-2e-5 2e-5]};
            title = 'AN1_clock_states';
            WHratio = 1.1;
            perchTextWidth = 0.7;
            obj.plot_2D('x_data',x_data,'y_data',y_data,'label_x',label_x,...
                'label_y',label_y,'sub_cols',1,'sub_rows',3,'names',legend, ...
                'lim_y',lim_y,'ax_legend',ax_legend,'title',title,'WHratio',WHratio,...
                'percTextWidth',perchTextWidth,'changeLineStyle',changeLineStyle);
        end

        function [mean_val, rmse, real_3sigma, est_3sigma] = get_stoch_params(obj,err,unc)

            % Reshape data as (simulation, time, variable)
            organized_err = permute(err,[3 2 1]);
            organized_unc = permute(unc,[3 2 1]);

            % Compute the mean and standard deviation of the estimated errors at each
            % timestep
            n = size(err,1);

            real_3sigma = zeros(n,size(unc,2));
            est_3sigma = zeros(n,size(unc,2));
            rmse = zeros(n,size(err,2));
            mean_val = zeros(n,size(err,2));

            for i = 1:n
                real_3sigma(i,:) = 3*std(organized_err(:,:,i),0,1);
                mean_val(i,:) = mean(organized_err(:,:,i),1);
                rmse(i,:) = sqrt(sum(organized_err(:,:,i).^2,1)/size(err,3));
                est_3sigma(i,:) =  mean(organized_unc(:,:,i),1);
            end

        end

    end
end

